version: '3'
services:
  api-server:
    #image: 'libari-server'
    build: ./server
    ports:
      - "5001:5001"
    depends_on:
      - mongo
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
  image-resize-service:
    build: ./image-worker
