version: '3'
services:
  api-server:
    #image: 'libari-server'
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env.prod
  image-resize-service:
    build: ./image-worker



