version: '3'
services:
  api-server:
    #image: 'libari-server'
    build: ./server
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - ./server/.env.dev
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  image-resize-service:
    build: ./image-worker
    env_file:
      - ./server/.env.dev
volumes:
  mongo-data: 
    driver: local


