version: '3'
services:
  api-server:
    image: strozzij/libari-api-server:latest
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env.prod
  image-resize-service:
    image: strozzij/libari-image-resize-service:latest
    build: ./image-worker



