name: Docker Image CI

on:
  push:
    branches: [ "main", "dockerize" ]
  pull_request:
    branches: [ "main" ]

jobs:

  create-docker-images:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Create .env.prod file
      run: |
        echo "Test: ${{ vars.PORT }}"
        echo MONGO_URL=${{ secrets.MONGO_URL }} >> ./server/.env.prod
        echo PORT=${{ vars.PORT }} >> ./server/.env.prod
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ./server/.env.prod
        echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> ./server/.env.prod
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> ./server/.env.prod
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ./server/.env.prod
        echo AWS_S3_BUCKET_REGION=${{ vars.AWS_S3_BUCKET_REGION }} >> ./server/.env.prod
        echo AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} >> ./server/.env.prod
        echo AWS_CLOUDFRONT_BASE_URL=${{ vars.AWS_CLOUDFRONT_BASE_URL }} >> ./server/.env.prod
        echo AWS_SQS_URL=${{ secrets.AWS_SQS_URL }} >> ./server/.env.prod

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker images
      run: | 
        ls -a
        docker-compose -f docker-compose.prod.yml build
        
    - name: Docker Push
      run: |
        docker images
